name: discount_card_app
description: CitizensRx Discount Card
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  modular_bloc_bind: ^1.0.1
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  asuka: ^2.0.0+1
  validatorless: ^1.2.1
  equatable: ^2.0.5
  flutter_dotenv: ^5.0.2
  google_maps_flutter: ^2.1.2  
  geolocator: ^8.2.0
  marker_icon: ^0.7.1
  label_marker: ^1.0.1
  custom_map_markers: ^0.0.2+1
  top_snackbar_flutter: ^2.1.1
  loading_animation_widget: ^1.2.0+3
  flutter_svg: ^0.22.0
  flutter_awesome_select: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: MontSerrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
    
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
  
    - family: Lexend
      fonts:
        - asset: assets/fonts/LexendDeca-Black.ttf
        - asset: assets/fonts/LexendDeca-Bold.ttf
        - asset: assets/fonts/LexendDeca-ExtraBold.ttf
        - asset: assets/fonts/LexendDeca-ExtraLight.ttf
        - asset: assets/fonts/LexendDeca-Light.ttf
        - asset: assets/fonts/LexendDeca-Medium.ttf
        - asset: assets/fonts/LexendDeca-Regular.ttf
        - asset: assets/fonts/LexendDeca-SemiBold.ttf
        - asset: assets/fonts/LexendDeca-Thin.ttf

  